default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  port: 5432
  username: postgres
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: quests_api_development

rubymine:
  <<: *default
  database: quests_api_development

test:
  <<: *default
  database: quests_api_test

production:
  <<: *default
  database: quests_api_production
