db:
  image: postgres:9.6.0
  # persist the database between containers by storing it in a volume
  volumes:
    - quest-api-postgres:/var/lib/postgresql/data

app:
  image: cedricwider/questapi_app:$DEPLOY_TAG
  env_file: .env
  environment:
    RAILS_ENV: $RAILS_ENV
  links:
    - db
  volumes:
    - quest-api-logs:/var/www/quest_api/log
  expose:
    - '3000'

# service configuration for production web server (Nginx)
web:
  image: cedricwider/questapi_web:$DEPLOY_TAG
  environment:
    CA_SSL: 'true'
  links:
    - app
  volumes:
    - quest-api-ssl:/var/www/ssl
  volumes_from:
    - app
  ports:
    - "80:80"
    - "443:443"
